# Generated by Django 2.2 on 2022-06-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertext',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
