# Generated by Django 2.2 on 2022-06-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlog', '0002_auto_20220620_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertext',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
