# Generated by Django 2.2 on 2022-06-21 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlog', '0003_auto_20220620_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertext',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
