# Generated by Django 2.2 on 2022-06-21 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlog', '0004_auto_20220620_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
