# Generated by Django 2.2 on 2022-07-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlog', '0007_auto_20220703_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
