# Generated by Django 2.2 on 2022-07-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlog', '0008_auto_20220703_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='pictures'),
        ),
    ]
