# Generated by Django 2.2 on 2022-07-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlog', '0009_auto_20220703_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
